// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSxA-RMR_WpMpt11l_lFMU2XX2aCM9Cao',
    appId: '1:1097437265095:web:81bf8291fd128baffa12e2',
    messagingSenderId: '1097437265095',
    projectId: 'ecommerce-be5b4',
    authDomain: 'ecommerce-be5b4.firebaseapp.com',
    storageBucket: 'ecommerce-be5b4.appspot.com',
    measurementId: 'G-6M25MYKJQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe87kWmwrLtywBJt1tc9Ff9ZtWmV0s5xM',
    appId: '1:1097437265095:android:e2c6140b4e72265dfa12e2',
    messagingSenderId: '1097437265095',
    projectId: 'ecommerce-be5b4',
    storageBucket: 'ecommerce-be5b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApcwW8J6hH_U2XBTN7FdSKuGydO-Rx8o0',
    appId: '1:1097437265095:ios:ad268a234fb38468fa12e2',
    messagingSenderId: '1097437265095',
    projectId: 'ecommerce-be5b4',
    storageBucket: 'ecommerce-be5b4.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApcwW8J6hH_U2XBTN7FdSKuGydO-Rx8o0',
    appId: '1:1097437265095:ios:ad268a234fb38468fa12e2',
    messagingSenderId: '1097437265095',
    projectId: 'ecommerce-be5b4',
    storageBucket: 'ecommerce-be5b4.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSxA-RMR_WpMpt11l_lFMU2XX2aCM9Cao',
    appId: '1:1097437265095:web:b29b78e66e24fb8bfa12e2',
    messagingSenderId: '1097437265095',
    projectId: 'ecommerce-be5b4',
    authDomain: 'ecommerce-be5b4.firebaseapp.com',
    storageBucket: 'ecommerce-be5b4.appspot.com',
    measurementId: 'G-QZTK3QJWCH',
  );
}
